/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2022-03-01 09:51:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>API-D</title>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"adminResources/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"adminResources/css/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"adminResources/css/vendor.bundle.addons.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"adminResources/css/style.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"adminResources/image/favicon.png\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-scroller\">\r\n");
      out.write("\t\t<!-- partial:partials/_navbar.html -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- partial -->\r\n");
      out.write("\t\t<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("\t\t\t<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- partial -->\r\n");
      out.write("\t\t\t<div class=\"main-panel\">\r\n");
      out.write("\t\t\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-lg-3 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"card bg-gradient-primary text-white text-center card-shadow-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal\">Total invoices</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"mb-0\">28893</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-lg-3 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"card bg-gradient-danger text-white text-center card-shadow-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal\">Total invoices</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"mb-0\">28893</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-lg-3 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"card bg-gradient-warning text-white text-center card-shadow-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal\">Total invoices</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"mb-0\">28893</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-lg-3 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"card bg-gradient-info text-white text-center card-shadow-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal\">Total invoices</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"mb-0\">28893</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body pb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Daily Sales</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex justify-content-between justify-content-lg-start flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mr-5 mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>56789</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal mb-0\">Online sales</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>12345</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal mb-0\">Sales in store</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body d-flex align-items-end p-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mt-auto w-100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"sales-legend\" class=\"chartjs-legend mt-2 mb-4\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<canvas id=\"chart-sales\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"card-title\">Activity</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"list d-flex align-items-center border-bottom pb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-sm rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face8.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper w-100 ml-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<b>Dobrick </b>published an article\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">2 hours ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"list d-flex align-items-center border-bottom py-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-sm rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper w-100 ml-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<b>Stella </b>created an event\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">3 hours ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"list d-flex align-items-center border-bottom py-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-sm rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face7.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper w-100 ml-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<b>Peter </b>submitted the reports\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">1 hours ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"list d-flex align-items-center border-bottom py-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-sm rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper w-100 ml-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<b>Nateila </b>updated the docs\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">1 hours ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"list d-flex align-items-center pt-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-sm rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face9.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper w-100 ml-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<b>Tom </b>uploaded the demo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">3 hours ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Traffic</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"w-50 mx-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<canvas id=\"traffic-chart\" width=\"100\" height=\"100\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text-center mt-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tTraffic for the day\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"card-description mb-5\">Traffic through the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsources google and facebook for the day</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"traffic-chart-legend\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"chartjs-legend traffic-chart-legend\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row grid-margin\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Order status</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"d-flex table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-sm btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-plus-circle-outline\"></i> Add\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-alert-circle-outline\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-delete-empty\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-printer\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group ml-auto mr-2 border-0 d-none d-md-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Search Here\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-cloud\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-dots-vertical\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"table-responsive mt-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"table mt-3 border-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Invoice</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Customer</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Ship</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Best Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Purchsed Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>50014</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>David Grey</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Italy</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$6300</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$2100</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><div class=\"badge badge-success badge-fw\">Progress</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>50015</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Stella Johnson</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Brazil</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$4500</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$4300</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><div class=\"badge badge-warning badge-fw\">Open</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>50016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Marina Michel</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Japan</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$4300</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$6440</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><div class=\"badge badge-danger badge-fw\">On\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thold</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>50017</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>John Doe</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>India</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$6400</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>$2200</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><div class=\"badge badge-success badge-fw\">Progress</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex align-items-center justify-content-between flex-column flex-sm-row mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"mb-3 mb-sm-0\">Showing 1 to 20 of 20 entries</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"pagination pagination-primary mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"mdi mdi-chevron-left\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item active\"><a class=\"page-link\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"mdi mdi-chevron-right\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 grid-margin\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Monthly Analytics</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"card-description\">Products that are creating the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmost revenue and their sales throughout the year and the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvariation in behavior of sales.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"js-legend\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"chartjs-legend mt-4 mb-5 analytics-legend\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"demo-chart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<canvas id=\"dashboard-monthly-analytics\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 grid-margin grid-margin-md-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"wrapper d-flex align-items-center justify-content-start justify-content-sm-center flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-md rounded\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper ml-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"font-weight-medium\">Tim Cook</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-muted\">timcook@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-info mb-0 font-weight-medium\">Designer</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 grid-margin grid-margin-md-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"wrapper d-flex align-items-center justify-content-start justify-content-sm-center flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-md rounded\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper ml-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"font-weight-medium\">Sarah Graves</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-muted\">Sarah@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-info mb-0 font-weight-medium\">Developer</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"wrapper d-flex align-items-center justify-content-start justify-content-sm-center flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-md rounded\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"adminResources/image/face3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper ml-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"font-weight-medium\">David Grey</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-muted\">David@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"text-info mb-0 font-weight-medium\">Support Lead</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- content-wrapper ends -->\r\n");
      out.write("\t\t\t\t<!-- partial:partials/_footer.html -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- partial -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- main-panel ends -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- page-body-wrapper ends -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- container-scroller -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- plugins:js -->\r\n");
      out.write("\t<script src=\"adminResources/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("\t<script src=\"adminResources/js/vendor.bundle.addons.js\"></script>\r\n");
      out.write("\t<!-- endinject -->\r\n");
      out.write("\t<!-- Plugin js for this page-->\r\n");
      out.write("\t<!-- End plugin js for this page-->\r\n");
      out.write("\t<!-- inject:js -->\r\n");
      out.write("\t<script src=\"adminResources/js/off-canvas.js\"></script>\r\n");
      out.write("\t<script src=\"adminResources/js/hoverable-collapse.js\"></script>\r\n");
      out.write("\t<script src=\"adminResources/js/template.js\"></script>\r\n");
      out.write("\t<script src=\"adminResources/js/settings.js\"></script>\r\n");
      out.write("\t<script src=\"adminResources/js/todolist.js\"></script>\r\n");
      out.write("\t<!-- endinject -->\r\n");
      out.write("\t<!-- Custom js for this page-->\r\n");
      out.write("\t<script src=\"adminResources/js/dashboard.js\"></script>\r\n");
      out.write("\t<!-- End custom js for this page-->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
